options:
  logging: CLOUD_LOGGING_ONLY
steps:
  - name: 'gcr.io/cloud-builders/docker'
    env: 
      - 'DOCKER_BUILDKIT=1'
    entrypoint: 'bash'
    args:
      - '-c'
      - | 
        docker build \
        -t ${_IMAGE_REPO_LOCATION}-docker.pkg.dev/${PROJECT_ID}/${_IMAGE_REPO_NAME}/blog:${REVISION_ID} \
        -t ${_IMAGE_REPO_LOCATION}-docker.pkg.dev/${PROJECT_ID}/${_IMAGE_REPO_NAME}/blog:latest \
        .

  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        docker push ${_IMAGE_REPO_LOCATION}-docker.pkg.dev/${PROJECT_ID}/${_IMAGE_REPO_NAME}/blog:${REVISION_ID}
        docker push ${_IMAGE_REPO_LOCATION}-docker.pkg.dev/${PROJECT_ID}/${_IMAGE_REPO_NAME}/blog:latest
  - name: 'blbulyandavbulyan/gcloud-helm:latest'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud container clusters get-credentials ${_GKE_CLUSTER_NAME} --region ${LOCATION} --project ${PROJECT_ID}
        result=$(eval helm ls | grep ${_CHART_NAME})
        if [ $? -ne "0" ]; then
        echo "Installing Helm Chart"
        helm install ${_CHART_NAME} deploy-templates/ -f deploy-templates/values.yaml --set-string image.repository="${_IMAGE_REPO_LOCATION}-docker.pkg.dev/${PROJECT_ID}/${_IMAGE_REPO_NAME}/blog:latest"
        else
        echo "Upgrading Helm Chart"
        helm upgrade ${_CHART_NAME} deploy-templates/ -f deploy-templates/values.yaml --set-string image.repository="${_IMAGE_REPO_LOCATION}-docker.pkg.dev/${PROJECT_ID}/${_IMAGE_REPO_NAME}/blog:latest"
        fi