{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "blog.serviceAccountName" . }}
  labels:
    {{- include "blog.labels" . | nindent 4 }}
  annotations:
    {{- if .Values.serviceAccount.gcp }}
    iam.gke.io/gcp-service-account: {{ .Values.serviceAccount.gcp | quote}}
    {{- end }}
automountServiceAccountToken: {{ .Values.serviceAccount.automount }}
{{- end }}
