INSERT INTO articles(author_id, title, text, publish_date) VALUES(1, 'Какая-то статья', 'Какой-то текст', CURRENT_TIMESTAMP);
INSERT INTO comments(article_id, author_id, text, publish_date) VALUES(1, 1, 'Очень интересный комментарий!', CURRENT_TIMESTAMP);
INSERT INTO comments(article_id, author_id, text, publish_date) VALUES(1, 1, 'Привет, это новый комментарий!', CURRENT_TIMESTAMP);
INSERT INTO comments(article_id, author_id, text, publish_date) VALUES(1, 1, 'Еще один комментарий для теста', CURRENT_TIMESTAMP);
INSERT INTO comments(article_id, author_id, text, publish_date) VALUES(1, 1, 'Этот комментарий очень важен', CURRENT_TIMESTAMP);
INSERT INTO comments(article_id, author_id, text, publish_date) VALUES(1, 1, 'Комментарий с длинным текстом, чтобы протестировать обрезку', CURRENT_TIMESTAMP);
INSERT INTO comments(article_id, author_id, text, publish_date) VALUES(1, 1, 'Последний комментарий', CURRENT_TIMESTAMP);
INSERT INTO comments(article_id, author_id, text, publish_date) VALUES(1, 1, 'Еще один комментарий', CURRENT_TIMESTAMP);
INSERT INTO comments(article_id, author_id, text, publish_date) VALUES(1, 1, 'Новый комментарий', CURRENT_TIMESTAMP);
INSERT INTO comments(article_id, author_id, text, publish_date) VALUES(1, 1, 'Пример комментария', CURRENT_TIMESTAMP);
INSERT INTO comments(article_id, author_id, text, publish_date) VALUES(1, 1, 'Комментарий от пользователя', CURRENT_TIMESTAMP);
INSERT INTO comments(article_id, author_id, text, publish_date) VALUES(1, 1, 'Тестовый комментарий', CURRENT_TIMESTAMP);
INSERT INTO comments(article_id, author_id, text, publish_date) VALUES(1, 1, 'Еще один тестовый комментарий', CURRENT_TIMESTAMP);
INSERT INTO comments(article_id, author_id, text, publish_date) VALUES(1, 1, 'Комментарий для проверки', CURRENT_TIMESTAMP);
INSERT INTO comments(article_id, author_id, text, publish_date) VALUES(1, 1, 'Комментарий номер 15', CURRENT_TIMESTAMP);
INSERT INTO comments(article_id, author_id, text, publish_date) VALUES(1, 1, 'Комментарий от анонима', CURRENT_TIMESTAMP);
INSERT INTO comments(article_id, author_id, text, publish_date) VALUES(1, 1, 'Комментарий смайлик 😃', CURRENT_TIMESTAMP);
INSERT INTO comments(article_id, author_id, text, publish_date) VALUES(1, 1, 'Комментарий с вопросом?', CURRENT_TIMESTAMP);
INSERT INTO comments(article_id, author_id, text, publish_date) VALUES(1, 1, 'Это длинный текст комментария, чтобы проверить, как обрабатывается длинный текст', CURRENT_TIMESTAMP);
INSERT INTO comments(article_id, author_id, text, publish_date) VALUES(1, 1, 'Комментарий для теста пагинации', CURRENT_TIMESTAMP);
INSERT INTO comments(article_id, author_id, text, publish_date) VALUES(1, 1, 'Комментарий номер 21', CURRENT_TIMESTAMP);
INSERT INTO comments(article_id, author_id, text, publish_date) VALUES(1, 1, 'Тест комментария', CURRENT_TIMESTAMP);
INSERT INTO comments(article_id, author_id, text, publish_date) VALUES(1, 1, 'Комментарий номер 23', CURRENT_TIMESTAMP);
INSERT INTO comments(article_id, author_id, text, publish_date) VALUES(1, 1, 'Еще один комментарий для проверки', CURRENT_TIMESTAMP);
INSERT INTO comments(article_id, author_id, text, publish_date) VALUES(1, 1, 'Тестовый комментарий номер 25', CURRENT_TIMESTAMP);
INSERT INTO comments(article_id, author_id, text, publish_date) VALUES(1, 1, 'Комментарий от нового пользователя', CURRENT_TIMESTAMP);
INSERT INTO comments(article_id, author_id, text, publish_date) VALUES(1, 1, 'Комментарий номер 27', CURRENT_TIMESTAMP);
INSERT INTO comments(article_id, author_id, text, publish_date) VALUES(1, 1, 'Просто комментарий', CURRENT_TIMESTAMP);
INSERT INTO comments(article_id, author_id, text, publish_date) VALUES(1, 1, 'Комментарий на русском языке', CURRENT_TIMESTAMP);
INSERT INTO comments(article_id, author_id, text, publish_date) VALUES(1, 1, 'Комментарий для тестирования', CURRENT_TIMESTAMP);
INSERT INTO comments(article_id, author_id, text, publish_date) VALUES(1, 1, 'Последний комментарий', CURRENT_TIMESTAMP);
INSERT INTO articles(author_id, title, text, publish_date) VALUES(1, 'Какая-то другая статья', 'Какой-то другой текст', CURRENT_TIMESTAMP);
INSERT INTO comments(article_id, author_id, text, publish_date) VALUES(2, 1, 'Тестовый комментарий номер 25', CURRENT_TIMESTAMP);
INSERT INTO comments(article_id, author_id, text, publish_date) VALUES(2, 1, 'Комментарий от нового пользователя', CURRENT_TIMESTAMP);
INSERT INTO comments(article_id, author_id, text, publish_date) VALUES(2, 1, 'Комментарий номер 27', CURRENT_TIMESTAMP);
INSERT INTO comments(article_id, author_id, text, publish_date) VALUES(2, 1, 'Просто комментарий', CURRENT_TIMESTAMP);
INSERT INTO comments(article_id, author_id, text, publish_date) VALUES(2, 1, 'Комментарий на русском языке', CURRENT_TIMESTAMP);
--INSERT INTO comments(article_id, author_id, text, publish_date) VALUES(2, 1, 'Комментарий для тестирования', CURRENT_TIMESTAMP);
--INSERT INTO comments(article_id, author_id, text, publish_date) VALUES(2, 1, 'Последний комментарий', CURRENT_TIMESTAMP);